require('./clamp/index.test');
require('./euclidean-distance/index.test');
require('./euclidean-distance/origin/index.test');
require('./float-to-integer/index.test');
require('./greater-than/0/index.test');
require('./index.test');
require('./round-float/index.test');
require('./under1/index.test');
require('./within-range/index.test');